// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Simulates different budget scenarios based on income and expense changes.
 *
 * - simulateBudgetScenarios - A function that simulates budget scenarios.
 * - SimulateBudgetScenariosInput - The input type for the simulateBudgetScenarios function.
 * - SimulateBudgetScenariosOutput - The return type for the simulateBudgetScenarios function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SimulateBudgetScenariosInputSchema = z.object({
  currentIncome: z.number().describe('The user\'s current monthly income.'),
  currentExpenses: z.number().describe('The user\'s current monthly expenses.'),
  incomeChange: z
    .number()
    .optional()
    .describe('The potential change in monthly income (positive or negative).'),
  expenseChanges: z
    .string()
    .optional()
    .describe(
      'A description of potential changes in expenses, including amounts and categories.'
    ),
});
export type SimulateBudgetScenariosInput = z.infer<
  typeof SimulateBudgetScenariosInputSchema
>;

const SimulateBudgetScenariosOutputSchema = z.object({
  scenarioDescription: z
    .string()
    .describe('A description of the simulated budget scenario.'),
  projectedIncome: z.number().describe('The projected monthly income.'),
  projectedExpenses: z.number().describe('The projected monthly expenses.'),
  netResult: z
    .number()
    .describe(
      'The net result (income minus expenses) of the simulated scenario.'
    ),
  impactAnalysis:
    z.string().describe('An analysis of the impact of the changes.'),
});
export type SimulateBudgetScenariosOutput = z.infer<
  typeof SimulateBudgetScenariosOutputSchema
>;

export async function simulateBudgetScenarios(
  input: SimulateBudgetScenariosInput
): Promise<SimulateBudgetScenariosOutput> {
  return simulateBudgetScenariosFlow(input);
}

const prompt = ai.definePrompt({
  name: 'simulateBudgetScenariosPrompt',
  input: {schema: SimulateBudgetScenariosInputSchema},
  output: {schema: SimulateBudgetScenariosOutputSchema},
  prompt: `You are a financial advisor helping users simulate budget scenarios.

  Based on the user's current financial situation and potential changes, you will project the impact on their budget.

Current Income: {{{currentIncome}}}
Current Expenses: {{{currentExpenses}}}
Potential Income Change: {{{incomeChange}}}
Potential Expense Changes: {{{expenseChanges}}}

Analyze the potential changes and provide a detailed breakdown of the simulated scenario, including:
- A description of the scenario.
- The projected income.
- The projected expenses.
- The net result (income minus expenses).
- An analysis of the overall impact.

Ensure the analysis is clear, concise, and actionable.

Here's an example of the kind of output you should strive for:

{
  "scenarioDescription": "This scenario simulates an increase in income and a decrease in expenses.",
  "projectedIncome": 6000,
  "projectedExpenses": 2500,
  "netResult": 3500,
  "impactAnalysis": "With the projected changes, your net income will increase significantly. This will allow you to save more or invest in other opportunities."
}

Consider these key points in your response:

- Be conversational
- Be precise with the numbers
- Be encouraging
`,
});

const simulateBudgetScenariosFlow = ai.defineFlow(
  {
    name: 'simulateBudgetScenariosFlow',
    inputSchema: SimulateBudgetScenariosInputSchema,
    outputSchema: SimulateBudgetScenariosOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
